name: Run job.py daily at 12:10 AM PST

on:
  schedule:
    - cron: "10 8 * * *"   # 08:10 UTC = 12:10 AM PST
  workflow_dispatch: {}      # allow manual run

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run script
        run: python job.py

      - name: Commit & push results (if job.py outputs files)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "Automated run: $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
            git push
          fi
